input("This should be True: {}".format(True and True))
input("This should be False: {}".format(False and True))
input("This should be False: {}".format(1 == 1 and 2 == 1))
input("This should be True: {}".format("test" == "test"))
input("This should be True: {}".format(1 == 1 and 2 != 1))
input("This should be True: {}".format(True and 1 == 1))
input("This should be False: {}".format(False and 0 != 1))
input("This should be True: {}".format(True and 1 == 1))
input("This should be False: {}".format("test" == "testing"))
input("This should be False: {}".format(1 != 0 and 2 == 1))
input("This should be True: {}".format("test" != "testing"))
input("This should be False: {}".format("test" == 1))
input("This should be True: {}".format(not (True and False)))
input("This should be False: {}".format(not (1 == 1 and 0 != 1)))
input("This should be False: {}".format(not (10 == 1 or 1000 == 1000)))
input("This should be False: {}".format(not (1 != 10 or 3 == 4)))
input("This should be True: {}".format(not ("testing" == "testing" and "Zed" == "Cool Guy")))
input("This should be True: {}".format(1 == 1 and (not("testing" == 1 or 1 == 0))))
input("This should be False: {}".format("chunky" == "bacon" and (not (3 == 4 or 3 ==3))))
input("This should be False: {}".format(3 == 3 and (not("testing" == "testing" or "Python" == "Something"))))
